name: Build CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches/modules-2
        key: ${{ runner.os }}-gradlemodules-${{ hashFiles('checksum.txt') }}
        restore-keys: |
          ${{ runner.os }}-gradlemodules-
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches/jars-3
        key: ${{ runner.os }}-gradlejars-${{ hashFiles('checksum.txt') }}
        restore-keys: |
          ${{ runner.os }}-gradlejars-
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches/build-cache-1
        key: ${{ runner.os }}-gradlebuildcache-${{ hashFiles('checksum.txt') }}
        restore-keys: |
          ${{ runner.os }}-gradlebuildcache-
    - uses: actions/cache@v1
      with:
        path: ~/.konan/cache
        key: ${{ runner.os }}-konancache-${{ hashFiles('checksum.txt') }}
        restore-keys: |
          ${{ runner.os }}-konancache-


    - name: Build Assessment Model
      env:
        AIR_NOW_API_KEY: ${{ secrets.AIR_NOW_API_KEY }}
        OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
      run: ./gradlew build